### ISSUE TITLE
Deprecate informatics docs repo

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/segmentation-labeling-app#118]
Related to this repo:
https://github.com/AllenInstitute/informatics_design_docs

We tried this out, we decided confluence was a better solution. Let's deprecate this by moving the contents to confluence:

- [x] move `ophys/segmentation` to confluence (Dan): http://confluence.corp.alleninstitute.org/pages/viewpage.action?pageId=80279411

- [x] move `ophys/classification` to confluence (Isaak): http://confluence.corp.alleninstitute.org/display/IT/Classification+Requirements
- [x] delete the repo (Dan)

**Comment by isaak-willett** [comment]
@djkapner I moved the classification document, so it's ready to delete!
