### ISSUE TITLE
annotations for superficial Slc

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/segmentation-labeling-app#127]
Small cell filter (85 pixels) is eliminating some ROIs, especially in superficial Slc line.

Tasks
- [ ] wait to know if any Suite2P parameters will change the looks of the marginal ROIs
- [ ] make small size filter more permissive. (histogram existing ROIs that are small-size excluded and choose a new npixel threshold that still excludes a lot)
- [ ] collect list of experiments to segment with input from science team.
- [ ] segment experiments
- [ ] determine N ROIs for annotation job with input from science team
- [ ] randomly sample N ROIs. Confirm than subset has a good number of previously small-size-excluded ROIs.
- [ ] generate `slapp` input for these ROIs @djkapner has some script(s)
- [ ] upload to s3
- [ ] launch job
- [ ] alert annotators

Validation
- [ ] job is running

**Comment by wbwakeman** [comment]
subsumed by #66
