### ISSUE TITLE
Create collection of ROIs for labeling question examples

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#15]
Survey the data to see what outputs look like.
Identify edge cases, difficult cases
Catalog these in a way that can be used to generate questions for which we need to know the answers in order to move forward with scientist labeller training.

**Comment by kschelonka** [comment]
We can deploy a separate SageMaker job for training/evaluation with a small, curated dataset, and have expert review.

**Comment by djkapner** [comment]
A small 5-cell dataset:
s3://dev.slapp.alleninstitute.org/UIUX/20200504160215

Made with this input json to `python -m slapp.transfers.upload --input_json <>`
```
{
        "s3_bucket_name": "dev.slapp.alleninstitute.org",
        "roi_manifests_ids": [2565, 2578, 2589, 2597, 2566],
        "log_level": "INFO",
        "prefix": "UIUX"
}
```
Other candidates could be selected and uploaded from that same experiment:
[104_candidate_ROIs.pdf](https://app.zenhub.com/files/249782006/d91e99f8-cf1c-4355-840b-eba8d31fe50e/download)
