### ISSUE TITLE
Usability testing with RAs/users

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#16]
In an online meeting with RAs that will be using the labeling tool, observe their use of the tool in order to observe potential pitfalls or opportunities for improvement.

Create data set for them to test with. Minimally, we should have 3 samples: Easy "is cell", Easy "not cell", Hard "is cell", Hard "not cell" -- work with scientists/others on the team to identify some of these examples. Each sample should come from a different movie so that the brightness/contrast/noise etc. are a little bit different.
Generate a few pages with the data set for them to work through.
Create a "script" for testing and recording feedback.

Tasks:
- [x] Schedule volunteers 
- [x] Write UX script (Kat)
- [x] Identify ROIs for testing (Dan)
- [x] Create UX test depoyment (Dan)
- [x] Meet to discuss test protocol (Kat)
- [x] Consolidate feedback (Kat)

Current Volunteers:
(Check if scheduled and add name of assignee)
- [x] Kate Roll (Kat)
- [x] Jerome Lecoq (Dan)
- [x] Shiella Caldejon (Isaak)
- [x] Natalia Orlova (Nick)

**Comment by kschelonka** [comment]
Notes are in our UX testing folder. Here is a [direct link](https://alleninstitute.sharepoint.com/sites/Pika/Shared%20Documents/Forms/AllItems.aspx?viewid=254b91db%2D2dbd%2D48ea%2Da028%2D6722415327bd&id=%2Fsites%2FPika%2FShared%20Documents%2FLabeling%20Tool%2FUX%5FTesting%5FNotes) to a consolidated list of action items for planning purposes.
