### ISSUE TITLE
Segmentation Labeling application support & monitoring

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#29]
Help folks use the tool. Answer questions as they arise.

- [x] Set up monitor for the labeling job in cloudwatch metrics, ROI-Labelers team (see [documentation](https://aws.amazon.com/blogs/machine-learning/tracking-the-throughput-of-your-private-labeling-team-through-amazon-sagemaker-ground-truth/))
- [ ] Create FAQ in repository for answering the questions scientists most want answers

**Comment by isaak-willett** [comment]
This ticket for the weeks of May 25th -> June 6th also covers the generation of a FAQ document, this document will cover the questions asked by the science team about the labeling app.
