### ISSUE TITLE
Generate document of questions for labeling tool edge cases

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#35]
to inform  how we deal with edge cases.
e.g. 
differences in labeling
"unsure"
"obvious" artifacts

This is the doc that will be used to iterate with science group to come up with annotation protocol.

**Comment by kschelonka** [comment]
How many annotators per label
Consensus vs. majority opinion
General guidelines -- e.g. how much of the cell does the ROI have to cover for it to be considered a cell
Certainty threshold (e.g. how sure do we tell the people they should be for a cell)

**Comment by njmei** [comment]
Document has been sent out and can be found on the pika sharepoint document storage page
