### ISSUE TITLE
Transformations for 2p movies to be displayed 

### ISSUE THREAD

**Issue by kschelonka** [AllenInstitute/segmentation-labeling-app#6]
To present the data for ROI labeling, we need 

1. Given the true frame rate (in FPS) and a desired frame rate lower than the original, temporally downsample the video with the following options:
- [x] Sample every `n` frames (where `n` is appropriate number for the new FPS)
- [x] Compute the mean of a rolling window of size `n`
- [x] Compute the max of a rolling window of size `n`

2. Given a coordinate pair, window size, and video:
- [x] Return a square window of appropriate size centered on the coordinate pair (a spatial sample of the movie)

3. Given the data for a movie represented in h5 format:
- [x] Convert to mp4 

4. Given a binary ROI mask in our JSON format and a stroke size in pixels:
- [x] Return list of coordinates for (inner) outline of ROI mask

5. ROI class method that writes required data to sqlite file
- [ ] Writes to specified sqlite file the required data for data upload.

**Comment by isaak-willett** [comment]
I bumped this up to an 8, it required implementing four modules and creating a method to do inner outline.
