### ISSUE TITLE
Data Transform Updates + Fixes

### ISSUE THREAD

**Issue by kschelonka** [AllenInstitute/segmentation-labeling-app#65]
~- [ ] The mask overlay .png should use alpha channel to show weights, not pixel colors. All pixels should be black [rgba(0,0,0,`x`]~
~- [ ] The mask overlay .png should be more transparent for lower weights~
- [x] Add arguments to tune color scale thresholds, and figure out generally effective values (solves issue with movies and images being too dark/light)
- [x] Use lower bitrate to reduce file sizes and improve performance
- [x] Change manifest extension to `json` from `jsonl`
- [x] Find out of SGT randomizes the manifest

**Comment by djkapner** [comment]
this is all already tracked here: https://github.com/AllenInstitute/segmentation-labeling-app/pull/54

**Comment by kschelonka** [comment]
Sounds good, but I'd like an issue rather than just a PR
