### ISSUE TITLE
Add play/pause buttons to be near trace

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#70]
Move play/pause to be closer to trace, or add additional play/pause buttons near trace

Also consider ability to use space bar to play/pause

**Comment by kschelonka** [comment]
This was fixed with small screen improvements (see PR #88)

**Comment by kschelonka** [comment]
I'm going to add improved keyboard support (escape to close maximized windows, space bar to play/pause) as a Nice to Hvae.
