### ISSUE TITLE
Add accompanying instructions/clarifications for tool

### ISSUE THREAD

**Issue by kschelonka** [AllenInstitute/segmentation-labeling-app#77]
- [x] Clarify which browsers we support (modern chrome/firefox)
- [x] Instruct users to refresh if images don't load on first try
- [x] Repeat/add instructions for interacting with trace
- [x] Click to expand/minimize images
- [x] Instruct users to check zoom level and set to 100% if having trouble seeing everything at once

**Comment by isaak-willett** [comment]
I added these instructions to the full instructions set on the sagemaker app.
![image.png](https://images.zenhubusercontent.com/5dde9d05537fdc0001b7a121/e77846f6-e151-4e2f-95fd-aa3ae34ba0f9)
