### ISSUE TITLE
Fix blurry video artifacts

### ISSUE THREAD

**Issue by isaak-willett** [AllenInstitute/segmentation-labeling-app#94]
# Overview
![Screen Shot 2020-05-12 at 1.50.22 PM.png](https://images.zenhubusercontent.com/5dde9d05537fdc0001b7a121/bf7d2f7d-d4f2-4694-924a-466aae49de7d)
It can be seen from the above screen shot that the objects in the frame are blurry. This could be the result of codec issues using constant bit rate over constant quality. To maintain constant quality in a video the bitrate must change throughout, restricting the bit rate leaves highly changing parts of the video without the quality of less changing sections.

Initial options to check out:
- [ ] constant quality encoding in imageio_ffmpeg
- [ ] Non constant bit rate change to provide less blurry artifacts in videos

# Notes
[ffmpeg constant quality docs](https://trac.ffmpeg.org/wiki/Encode/VP9)
[bit rates in videos](https://help.encoding.com/knowledge-base/article/understanding-bitrates-in-video-files/)
[ffmpeg commands in imageio](https://imageio.readthedocs.io/en/stable/format_ffmpeg.html)

# Validation Criteria:
Both full-size and 128x128 videos play on modern Chrome and Firefox browsers. The videos load and play consistently, line up with the traces, there are no visible artifacts, and they can be used by labelers to make classification decisions. This should be demonstrated for videos that come from at least five experiments, since artifacts are not present for every video. For testing, create a simple webpage that plays the videos from local files. For final validation, create a SageMaker job and invite the dev team to test.

**Comment by njmei** [comment]
imageio-ffmpeg looks to literally just stitch together an ffmpeg command. Here is the relevant line for what modifying 'bitrate' does. Which is probably not quite the desired thing for the vp9 encoder.

https://github.com/imageio/imageio-ffmpeg/blob/974e92e699676822971d66765a2787ecac3a0788/imageio_ffmpeg/_io.py#L383

**Comment by kschelonka** [comment]
Updated title and validation criteria.

**Comment by njmei** [comment]
Resolved by #100
